vich_uploader:
    db_driver: orm

    metadata:
        type: attribute

    mappings:
        product_images:
            uri_prefix: /images
            upload_destination: '%kernel.project_dir%/assets/images'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
            inject_on_load: true
            delete_on_update: true
            delete_on_remove: true