vich_uploader:
    db_driver: orm

    mappings:
        product_images:
            uri_prefix: /images
            upload_destination: '%kernel.project_dir%/assets/images'
            namer: Vich\UploaderBundle\Naming\UniqidNamer
