services:
    _defaults:
        autowire: true      # Injecte automatiquement les dépendances dans vos services.
        autoconfigure: true # Enregistre automatiquement vos services comme commandes, abonnés d'événements, etc.

    # Enregistre automatiquement les services dans le dossier src/
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    
    App\Service\StripePaymentService:
        arguments:
            $stripeSecretKey: '%env(STRIPE_SECRET_KEY)%'


    Symfony\Component\Mailer\MailerInterface: '@mailer'
    Symfony\Component\Mailer\Transport\TransportInterface: '@mailer.transport'

parameters:
    app.path.product_images: /uploads/images/products
